dist: trusty
language: python
python:
  - "3.5"
#  - "3.5-dev"  # 3.5 development branch
#  - "3.6"
#  - "3.6-dev"  # 3.6 development branch

before_install:
  # add rsa
  - sudo apt-get install sshpass -y
  - sshpass -V
  - echo -e 'testbuild\ntestbuild' | sudo passwd $USER
  - ssh-keygen -t rsa -b 4096 -C 'build@travis-ci.org' -f $HOME/.ssh/id_rsa -N ''
  - sshpass -p 'testbuild' ssh-copy-id -i $HOME/.ssh/id_rsa.pub -o StrictHostKeyChecking=no $USER@localhost 

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python3 -m unittest discover -p "test_*.py" test