language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  # add rsa
  - export user=`whoami`
  - ssh-keygen -t rsa -b 4096 -C 'build@travis-ci.org' -f $HOME/.ssh/id_rsa -N ''
  - ssh-copy-id -i $HOME/.ssh/id_rsa.pub -o StrictHostKeyChecking=no user@localhost 

  - python3 -m unittest discover -p "test_*.py" test